CREATE TABLE ESTADOS (cod INT PRIMARY KEY,
                      nome VARCHAR(100) NOT NULL,
                      sigla VARCHAR(2) NOT NULL);


CREATE TABLE MUNICIPIOS (cod_uf INT NOT NULL,
                         cod INT PRIMARY KEY,
                         nome VARCHAR(100) NOT NULL);


ALTER TABLE MUNICIPIOS
ADD CONSTRAINT FK_MUNICIPIO_ESTADO FOREIGN KEY (cod_uf) REFERENCES ESTADOS(cod);


SELECT E.nome AS NOME_ESTADO, M.nome AS NOME_MUNICIPIOS
FROM ESTADOS E, MUNICIPIOS M
WHERE M.cod_uf = E.cod;


SELECT * FROM ESTADOS;